apiVersion: v2
name: keycloak
description: A Helm chart for keycloak
type: application
version: 0.1.0
appVersion: "1.16.0"
dependencies:
- name: postgres-operator
  repository: https://opensource.zalando.com/postgres-operator/charts/postgres-operator
  version: 1.12.2
