{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: keycloak
  namespace: {{ .Release.Namespace }}
  labels:
  annotations:
  {{- with .Values.ingress.extraAnnotations }}
      {{- toYaml . | nindent 4 }}
  {{- end }}
    nginx.ingress.kubernetes.io/affinity: cookie
    nginx.ingress.kubernetes.io/affinity-mode: persistent
    ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "128k"
    nginx.ingress.kubernetes.io/configuration-server: |
      location /auth/admin {
        deny all;
        return 403;
      }
spec:
  ingressClassName: {{ .Values.ingress.className }}
  {{- if .Values.ingress.tlsSecret }}
  tls:
  - hosts:
      - {{ .Values.ingress.hostname }}
    secretName: {{ .Values.ingress.tlsSecret }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.hostname }}
      http:
        paths:
          - path: "{{ .Values.httpRelativePath }}"
            pathType: ImplementationSpecific
            backend:
              serviceName: keycloak
              servicePort: http
{{- end }}
