apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: {{ .Values.pgcluster.name }}-postgresql-cluster
  namespace: {{ .Release.Namespace }}
  labels:
    application: keycloak
#    environment: demo
spec: 
  dockerImage: {{ .Values.pgcluster.image }}
  teamId: "keycloak"
  numberOfInstances: {{ .Values.pgcluster.replica }}
  users:  # Application/Robot users
    zalando:
    - superuser
    - createdb
    keycloak: []
  databases:
    keycloak: keycloak
#  usersWithSecretRotation:
#  - foo_user
#  usersWithInPlaceSecretRotation:
#  - flyway
#  - bar_owner_user
  enableMasterLoadBalancer: {{ .Values.pgcluster.loadBalancer.master }}
  enableReplicaLoadBalancer: {{ .Values.pgcluster.loadBalancer.replica }}
  enableConnectionPooler: false # enable/disable connection pooler deployment
  enableReplicaConnectionPooler: false # set to enable connectionPooler for replica service
  enableMasterPoolerLoadBalancer: false
  enableReplicaPoolerLoadBalancer: false
  allowedSourceRanges:  # load balancers' source ranges for both master and replica services
  - 127.0.0.1/32
  preparedDatabases: {}
  postgresql:
    version: {{ .Values.pgcluster.postgresVersion | quote }}
    parameters:  # Expert section
      shared_buffers: "32MB"
      max_connections: "100"
      log_statement: "all"
  volume:
    size: {{ .Values.pgcluster.volume.size }}
    storageClass: {{ .Values.global.storageClass }}
#    selector:
#      matchExpressions:
#        - { key: flavour, operator: In, values: [ "banana", "chocolate" ] }
#      matchLabels:
#        environment: dev
#        service: postgres
  
  additionalVolumes:
    # - name: data
    #   mountPath: /home/postgres/pgdata/partitions
    #   targetContainers:
    #     - postgres
    #   volumeSource:
    #     PersistentVolumeClaim:
    #       claimName: pvc-postgresql-data-partitions
    #       readyOnly: false    
  resources: 
    {{- toYaml .Values.pgcluster.resources | nindent 4 }}
  patroni:
    failsafe_mode: false
    initdb:
      encoding: "UTF8"
      locale: "en_US.UTF-8"
      data-checksums: "true"
#    pg_hba:
#      - hostssl all all 0.0.0.0/0 md5
#      - host    all all 0.0.0.0/0 md5

# overwrite custom properties for connection pooler deployments
  connectionPooler:
    numberOfInstances: {{ .Values.pgcluster.connectionPooler.instances }}
    mode: "transaction"
    schema: "pooler"
    user: "pooler"
    resources:
      requests:
        cpu: 100m
        memory: 250Mi
      limits:
        cpu: "500m"
        memory: 500Mi

  initContainers:
  - name: date
    image: coredgeio/busybox
    command: [ "/bin/date" ]
  {{- if .Values.pgcluster.monitoring.enabled }}
  sidecars:
  - name: "metrics-exporter"
    image: "coredgeio/postgres-exporter:v0.15.0"
    ports:
    - name: exporter
      containerPort: 9187
      protocol: TCP
    resources:
      limits:
        cpu: 500m
        memory: 500Mi
      requests:
        cpu: 100m
        memory: 100Mi
    env:
      - name: "DATA_SOURCE_URI"
        value: "$(POD_NAME)/postgres?sslmode=require"
      - name: "DATA_SOURCE_USER"
        value: "$(POSTGRES_USER)"
      - name: "DATA_SOURCE_PASS"
        value: "$(POSTGRES_PASSWORD)"
      - name: "PG_EXPORTER_AUTO_DISCOVER_DATABASES"
        value: "true"
  {{- end }}
---
{{- if .Values.pgcluster.monitoring.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.pgcluster.name }}-postgresql-cluster-master-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    spilo-role: master
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9187"
spec:
  type: ClusterIP
  ports:
    - name: exporter
      port: 9187
      targetPort: exporter
  selector:
    application: keycloak
    cluster-name: {{ .Values.pgcluster.name }}-postgresql-cluster
    spilo-role: master
{{- end }}