apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: {{ .Release.Namespace }}
  labels:
    app: keycloak
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
    nodePort: {{ .Values.service.nodePorts.http }}
  - name: https
    port: 8443
    targetPort: 8443
    protocol: TCP
    nodePort: {{ .Values.service.nodePorts.https }}
  selector:
    app: keycloak
  type: {{ .Values.service.type }}
---
# headless-svc.yml
apiVersion: v1
kind: Service
metadata:
  name: keycloak-headless
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: keycloak
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
  - name: https
    protocol: TCP
    port: 8443
    targetPort: 8443
