annotations:
  category: DeveloperTools
  licenses: Apache-2.0
apiVersion: v2
appVersion: 20.0.3
dependencies:
- name: common
  repository: https://charts.bitnami.com/bitnami
  version: 2.x.x
  tags:
  - bitnami-common
- name: postgres-operator
  repository: https://opensource.zalando.com/postgres-operator/charts/postgres-operator
  version: 1.10.0
description: Keycloak is a high performance Java-based identity and access management
  solution. It lets developers add an authentication layer to their applications with
  minimum effort.
home: https://bitnami.com
icon: https://bitnami.com/assets/stacks/keycloak/img/keycloak-stack-220x234.png
keywords:
- keycloak
- access-management
name: keycloak
version: 15.1.3
