apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.fullname" . }}-envvars
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
    app.kubernetes.io/component: grafana
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
  GF_SECURITY_ADMIN_USER: {{ .Values.admin.user | quote }}
  {{- if .Values.imageRenderer.enabled }}
  {{- $domain := .Values.clusterDomain }}
  {{- $namespace := .Release.Namespace }}
  GF_RENDERING_SERVER_URL: "http://{{ include "common.names.fullname" . }}-image-renderer.{{ $namespace }}.svc.{{ $domain }}:{{ .Values.imageRenderer.service.ports.imageRenderer }}/render"
  GF_RENDERING_CALLBACK_URL: "http://{{ include "common.names.fullname" . }}.{{ $namespace }}.svc.{{ $domain }}:{{ .Values.service.ports.grafana }}/"
  {{- end }}
  {{- if .Values.plugins }}
  GF_INSTALL_PLUGINS: {{ .Values.plugins | quote }}
  {{- else }}
  GF_INSTALL_PLUGINS: ""
  {{- end }}
  GF_PATHS_PLUGINS: "/opt/coredge/grafana/data/plugins"
  GF_AUTH_LDAP_ENABLED: {{ .Values.ldap.enabled | quote }}
  GF_AUTH_LDAP_CONFIG_FILE: "/opt/coredge/grafana/conf/ldap.toml"
  GF_AUTH_LDAP_ALLOW_SIGN_UP: {{ .Values.ldap.allowSignUp | quote }}
  GF_PATHS_PROVISIONING: "/opt/coredge/grafana/conf/provisioning"
  GF_PATHS_CONFIG: "/opt/coredge/grafana/conf/grafana.ini"
  GF_PATHS_DATA: "/opt/coredge/grafana/data"
  GF_PATHS_LOGS: "/opt/coredge/grafana/logs"
  ## Grafana Auth Keycloak Envs....
  GF_SERVER_ROOT_URL: http://13.233.196.43:30000/
  GF_AUTH_GENERIC_OAUTH_ENABLED: 'True'
  GF_AUTH_GENERIC_OAUTH_ALLOW_SIGN_UP: 'True'
  GF_AUTH_GENERIC_OAUTH_AUTO_LOGIN: 'False'
  GF_AUTH_GENERIC_OAUTH_ALLOWED_ORGANIZATIONS: ''
  GF_AUTH_GENERIC_OAUTH_NAME: Keycloak
  GF_AUTH_GENERIC_OAUTH_CLIENT_ID: grafana-oauth
  GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: qkwR4v41o0E7Ldohsf8NNXAa6AgQuMlv
  GF_AUTH_GENERIC_OAUTH_SCOPES: openid email profile offline_access roles
  GF_AUTH_GENERIC_OAUTH_AUTH_URL: https://13.233.134.251:32045/realms/grafana/protocol/openid-connect/auth
  GF_AUTH_GENERIC_OAUTH_TOKEN_URL: https://13.233.134.251:32045/realms/grafana/protocol/openid-connect/token
  GF_AUTH_GENERIC_OAUTH_API_URL: https://13.233.134.251:32045/realms/grafana/protocol/openid-connect/userinfo
  GF_AUTH_GENERIC_OAUTH_ROLE_ATTRIBUTE_PATH: contains(roles[*], 'Admin') && 'Admin' || contains(roles[*], 'Editor') && 'Editor' || 'Viewer'
  GF_AUTH_GENERIC_OAUTH_EMAIL_ATTRIBUTE_PATH: email
  GF_AUTH_GENERIC_OAUTH_LOGIN_ATTRIBUTE_PATH: username
  GF_AUTH_GENERIC_OAUTH_NAME_ATTRIBUTE_PATH: full_name
  GF_AUTH_GENERIC_OAUTH_GROUPS_ATTRIBUTE_PATH: groups
  GF_AUTH_GENERIC_OAUTH_ROLE_ATTRIBUTE_STRICT: 'True'
  GF_AUTH_GENERIC_OAUTH_TLS_SKIP_VERIFY_INSECURE: 'True'
  GF_AUTH_GENERIC_OAUTH_SKIP_ORG_ROLE_SYNC: 'True'
  GF_AUTH_SIGNOUT_REDIRECT_URL: https://13.233.134.251:32045/realms/grafana/protocol/openid-connect/logout?post_logout_redirect_uri=http%3A%2F%2F13.233.196.43%3A30000%2Flogin&client_id=grafana-oauth
